### PR TITLE
Add LICENSE to root in order to properly uncopyright the code

### PR DESCRIPTION
**Pull request by rogersachan**
By putting the license in a subfolder, this leaves all the code in the other folders [copyrighted](https://choosealicense.com/no-license/). This PR amends the issue.

### CODE REVIEW

**Comment by Pomax** [comment]
This is a different license from what is already in the repo.

**Comment by rogersachan** [comment]
What license is it? The bundle has this license.

**Comment by rogersachan** [comment]
@Pomax I have now copied the exact license from the bundle to the root directory.

**Comment by Pomax** [comment]
thanks

**Pull request merged**
