### PR TITLE
Issue #99 : withTouch() touchstart event was relying on direct access to...

### PR DESCRIPTION
**Pull request by uofajillian**
Issue #99 : the withTouch() touchstart event handler was relying on direct access to the Processing.eventHandlers array to remove any existing mouse event handlers.

Instead of exposing Processing.eventHandlers array directly, this change exposes a method called detachEventHandlersByTypeMatch() which takes a regex of event types, iterates through the list of existing event handlers, and detaches the handlers that match.

The withTouch() touchstart handler then calls detachEventHandlersByTypeMatch() with a regex that matches the desired mouse events.

### CODE REVIEW

**Comment by karger** [comment]
I'm encountering this same bug.  Do you know why the PR hasn't been merged yet?

**Comment by Pomax** [comment]
mostly because at the time I was waiting for some tests. Landing code like this needs a few tests even if they're manual, and if @uofajillian has no time for them (given the PR age, understandable) either I or someone else will have to fork the PR and add tests before we can land this. It's a big enough PR to potentially introduce bugs, or regress, so without tests, it can't land

**Comment by uofajillian** [comment]
Yes, my apologies for letting this slide.  I added one manual test, but found that even though my fix appears to repair the issues I was seeing in my apps, it wasn't fixing the issue in the test.

I've got some time this week, will have another look at it.

**Comment by uofajillian** [comment]
Ok, I think I've resolved the issues with my code change, see commit 2da9649.

But unfortunately, I'm still only able to test them using a manual test.  I've verified the manual test with the re-built version of processing.min.js (not committed) on iOS Safari, iOS Chrome v39, and Android Chrome v43, as well as non-touch OSX Chrome v43 and OSX Firefox v38.

**Comment by Pomax** [comment]
manual tests for now are fine, really. It's probably worth turning those into Phantom tests at some point, to run during the build/test steps, but that's definitely a thing to do later

**Comment by karger** [comment]
Likely unimportant, but I've just tested my problematic touch-event processing.js code under processing.js 1.4.1 and it works fine---so this problem is a regression that crept in after that release.

**Comment by Pomax** [comment]
I suspect that'll have happened when the "single 20,000 line file" was split up into modules instead. I'm currently at a company all-hands but will be back coming sunday so I should be able to look at this in more detail and hopefully merge.

**Comment by timgvandijk** [comment]
This thread is quite old, but for what it's worth, I had similar issues with touch events and the Processing.eventHandlers array being out of scope, and this PR seems to solve them - with the one remark that the detachEventHandlersByType method needs to loop over p.eventHandlers rather than eventHandlers.

**Comment by Pomax** [comment]
@timgvandijk would you be willing to create a PR fork with those changes added in?

**Comment by frogg** [comment]
@Pomax I've done the necessary changes and created a pull request #277.

**Comment by Pomax** [comment]
superceded by #277, which landed

**Pull request closed without merging**
