### PR TITLE
quick-fix for issue #92

### PR DESCRIPTION
**Pull request by Domiii**

### CODE REVIEW

**Comment by Pomax** [comment]
Based on https://github.com/processing-js/processing-js/issues/92#issuecomment-147040970 I'm going to have to close this PR, though, as it would cease to support essential Processing functionality by taking away framerate control...

**Comment by jwdunn1** [comment]
Framerate control, along with a fallback for older browsers. (It works back to Safari 5 for example.)

Two small changes are required...
1) Replace source line 4118 with: requestAnimationFrame(_doDraw);

2) Then, replace source lines 4079-4086 with:
requestAnimationFrame= (function(){
      return window.requestAnimationFrame ||
             window.webkitRequestAnimationFrame ||
             window.mozRequestAnimationFrame    ||
             function( callback ){
                var _h= function(){callback(Date.now());};
                window.setTimeout(_h, curMsPerFrame);
             };
     })();

    // requestAnimationFrame edit
    var _now, _then=0, _doDraw= function(t) {
      requestAnimationFrame(_doDraw);
        if (!looping) { return; }
        _now= t;
        var _delta= _now - _then;
        if (_delta > curMsPerFrame) {  // regulate the framerate
            _then= _now - (_delta % curMsPerFrame);

            curSketch.onFrameStart();
            p.redraw();
            curSketch.onFrameEnd();
        }
    };

Do I fork and create another PR with these changes or do you want to go ahead and make the change?

**Comment by Domiii** [comment]
@jwdunn1 Your change looks great! Feel free to make the PR. It is your change, you should own it :)

**Comment by jwdunn1** [comment]
Domiii, I made the PR with our combined changes. You can close this one.

**Comment by Domiii** [comment]
@jwdunn1 Thank you!

**Pull request closed without merging**
