### PR TITLE
I changed utf8 to utf-8

### PR DESCRIPTION
**Pull request by AwesomeWebMaster10**

### CODE REVIEW

**Comment by GoToLoop** [comment]
Actually the most formal way is `<meta charset="UTF-8">` as we can verify here:
http://www.w3Schools.com/tags/att_meta_charset.asp  

Since I'm very lazy, I'd go w/ `<meta charset=utf8>`.  :laughing:

**Comment by Pomax** [comment]
you need the quotes, because the attribute value has a dash in it, but in HTML (unlike XHMTL) case gets ignored.

**Comment by GoToLoop** [comment]
> You need the quotes, because the attribute value has a dash in it, ...

My lazy (and against HTML rules) `<meta charset=utf8>` doesn't have and dash in it!  :dizzy_face:  
As I was clearly pointing out, modern browsers are very forgivable to HTML rules.  
But if some1 is looking for the most correct way, the link I've provided above is authoritative.  :cop:

**Comment by Pomax** [comment]
I prefer w3.org over w3schools, the latter's traditionally had less than reliable information (although it's gotten better recently)

**Comment by GoToLoop** [comment]
Even in there: https://www.w3.org/TR/html-markup/meta.charset.html#meta.charset
The string "UTF-8" is recognized the official name for this encoding:  

> For documents in the XML syntax, the value of the charset attribute must be a case-insensitive match for the string "UTF-8".

Regardless, I still haven't spotted any modern browser which doesn't recognize "utf8".
If the objective of this pull is to have the most correct version, it shoulda been "UTF-8", not "utf-8".  :stuck_out_tongue:

**Comment by Pomax** [comment]
lowercase is not "halfway", it's correct HTML5 syntax, which `<!doctype html>` tells the browser to use.

**Pull request merged**
